### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by BaReinhard** [AlbericoD/twitch-extension-without-js-framework#1]
using node 8.11.1
npm install
then try running start

```Entrypoint LiveConfiguration = LiveConfiguration.bundle.js
[0] ./src/panel/index.js 3.21 KiB {3} [not cacheable] [built] [failed] [1 error]
[1] ./src/mobile/index.js 3.06 KiB {2} [not cacheable] [built] [failed] [1 error]
[2] ./src/video-component/index.js 3.06 KiB {4} [not cacheable] [built] [failed] [1 error]
[3] ./src/video-fullscreen/index.js 3.06 KiB {5} [not cacheable] [built] [failed] [1 error]
[4] ./src/configuration/index.js 3.06 KiB {0} [not cacheable] [built] [failed] [1 error]
[5] ./src/live-configuration/index.js 3.06 KiB {1} [not cacheable] [built] [failed] [1 error]

ERROR in ./src/panel/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/babel-loader/lib/index.js:10:11)
    at Module._compile (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at loadLoader (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/loader-runner/lib/loadLoader.js:18:17)
    at iteratePitchingLoaders (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/NormalModule.js:292:3)
    at NormalModule.build (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/NormalModule.js:438:15)
    at Compilation.buildModule (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/Compilation.js:702:10)
    at moduleFactory.create (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/Compilation.js:1074:12)
    at factory (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
    at hooks.afterResolve.callAsync (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/tapable/lib/Hook.js:154:20)
    at resolver (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
    at process.nextTick (/Users/brett.reinhard/pod/twitch-extension-without-js-framework/node_modules/webpack/lib/NormalModuleFactory.js:346:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by BaReinhard** [comment]
Among other errors, but this seems to be the main issue.

**Comment by AlbericoD** [comment]
thanks, i'm already applying the fix, i forgot to put the --save-dev flag in the babel module.
